### ISSUE TITLE
The front-end model weights is not available

### ISSUE THREAD

**Issue by StiphyJay** [MAC-VO/MAC-VO#1]
Thanks for the great works!

However, the front-end model weights is not available.

**Comment by MarkChenYutian** [comment]
Hi, the frontend network weights are released in the `Release` of this repository. You can also access it using the url below:

https://github.com/MAC-VO/MAC-VO/releases/tag/model

If you have any additional question, feel free to follow up : )

**Comment by StiphyJay** [comment]
Thanks!
