### ISSUE TITLE
IPhone 15+ Stereo demo

### ISSUE THREAD

**Issue by pablovela5620** [MAC-VO/MAC-VO#2]
Hi, congrats on the release! I saw that you all had demoed using a ZED stereo camera, has there been consideration making it possible to use Spatial video from Iphone 15+ phones? this would make this method much more accessible (I haven't yet looked but I'm assuming only stereo images are required and not calibrated rectified images?)

https://blog.mikeswanson.com/spatial/

here's a blog on how to convert from MV-HEVC (spatial stereo video format) to separate stereo videos. This would be an awesome addition to make it easy for folks to try the method on their own videos (since there's a whole lot more IPhones then ZED cameras)

**Comment by haleqiu** [comment]
@pablovela5620 Thank you for the suggestions. As long as the camera is calibrated, this is feasible.
